name: "Build docs"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4 
      with:
        python-version: '3.9' 
    - name: Install dependencies
      run: |
        pip install "numpydoc==1.1.0" "Sphinx==4.4.0" "furo" .
    - name: Build docs
      run: sphinx-build docs/source docs/_build
    - name: Commit changes to docs
        run: |
          cd ./gh-pages
          cp -R ../master/docs/* ./
          git config --local user.email ""
          git config --local user.name "github-actions"
          git add -A
          if ! git diff-index --quiet HEAD; then
            git commit -m "auto: Rebuild docs."
            git  push
          else
            echo No commit made because the docs have not changed.
          fi