name: "Build docs"
on: 
- push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4 
      with:
        python-version: '3.9' 
    - name: Install dependencies
      run: |
        pip install "numpydoc==1.1.0" "Sphinx==4.4.0" "furo" .
    - name: Build docs
      run: sphinx-build docs/source docs/_build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site